entrypoint: gunicorn -b :$PORT main:app 
runtime: python38 


handlers:
  # Serve all static files with url ending with a file extension
  - url: /(.*\..+)$
    static_files: build/\1
    upload: build/(.*\..+)$
  - url : /api_call
    script: main.app 
      #  static_files: build/index.html
      #  upload: index.html
  # Catch all handler to index.html
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
    secure: always

