# This is a basic workflow to help you get started with Actions

name: Deploy to GAE

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ gcloud-config ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    name: Build Front End using Node.js (npm)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "14.x"

      - name: Install dependencies
        run: npm install
        
      - name: Fix issues with install
        run: npm audit fix

      - name: Run build
        run: CI=false npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    name: Deploying to Google Cloud
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        deliverables: app.yaml cron.yaml build
        project_id: seraphic-bliss-298801
        credentials: ${{ secrets.GCP_CREDENTIALS }}
